apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - secret.yaml

replicas:
  - name: php-api
    count: 3

commonLabels:
  environment: prod
