apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - secret.yaml

patches:
  - target:
      kind: ConfigMap
      name: mariadb-config
    patch: |-
      - op: replace
        path: /data/database
        value: "myapp_dev"

commonLabels:
  environment: dev
