apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - secret.yaml

patches:
  - target:
      kind: ConfigMap
      name: flyway-config
    patch: |-
      - op: replace
        path: /data/FLYWAY_URL
        value: "jdbc:mysql://mysql.dev.svc.cluster.local:3306/myapp_dev"

commonLabels:
  environment: dev
