apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - secret.yaml

patches:
  - target:
      kind: ConfigMap
      name: flyway-config
    patch: |-
      - op: replace
        path: /data/FLYWAY_URL
        value: "jdbc:mysql://mysql.staging.svc.cluster.local:3306/myapp_staging"

commonLabels:
  environment: staging
