apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - secret.yaml

replicas:
  - name: php-api
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: php-api-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: "staging"

commonLabels:
  environment: staging
