apiVersion: v1
kind: Secret
metadata:
  name: php-api-secrets
type: Opaque
stringData:
  MYSQL_HOST: "${MYSQL_HOST}"
  MYSQL_DATABASE: "${MYSQL_DATABASE}"
  MYSQL_USER: "${MYSQL_USER}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  REDIS_HOST: "${REDIS_HOST}"
