apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - secret.yaml

patches:
  # Production database name
  - target:
      kind: ConfigMap
      name: mariadb-config
    patch: |-
      - op: replace
        path: /data/database
        value: "myapp"
  # Production resource limits
  - target:
      kind: StatefulSet
      name: mariadb
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 2000m
  # Production storage
  - target:
      kind: StatefulSet
      name: mariadb
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: "50Gi"

commonLabels:
  environment: prod
