apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - migration-job.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: flyway-migrations
  app.kubernetes.io/component: database
  app.kubernetes.io/managed-by: kustomize
