apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - secret.yaml

replicas:
  - name: php-api
    count: 1

patches:
  - target:
      kind: ConfigMap
      name: php-api-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: "development"
      - op: replace
        path: /data/APP_DEBUG
        value: "true"

commonLabels:
  environment: dev
